version: "3.5"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    container_name: city-backend
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_connect_back=1 remote_port=9988 max_nesting_level=512 profiler_enable=0 idekey = \"PHPSTORM\""
      PHP_IDE_CONFIG: "serverName=localhost"
    networks:
      - proxynet
    volumes:
      - ./:/var/www

  webserver:
    image: nginx:alpine
    ports:
      - "8082:80"
    container_name: city-webserver
    networks:
      - proxynet
    volumes:
      - ./:/var/www
      - ./environment/configs/nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: postgres:9.6
    ports:
      - "5479:5432"
    container_name: city-db
    volumes:
      - city-data:/var/lib/postgresql/data
    networks:
      - proxynet
    environment:
      #- POSTGRES_USER=${DB_USERNAME}
      #- POSTGRES_PASSWORD=${DB_PASSWORD}
      #- POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=city-expert
      - POSTGRES_PASSWORD=312938712983712ajdsbajsbdajd
      - POSTGRES_DB=city-expert
      - TZ=Europe/Moscow

  queue:
    image: redis
    ports:
      - "6388:6379"
    container_name: city-queue
    networks:
      - proxynet

  file-storage:
    image: minio/minio
    container_name: city-file-storage
    volumes:
      - file-storage:/data
    ports:
      - "9022:9000"
    environment:
      - MINIO_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${AWS_S3_SECRET_KEY}
    networks:
      - proxynet
    command: server /data

networks:
  proxynet:
    name: city-expert

volumes:
  city-data:
  file-storage:
